import Head from 'next/head'
import ArrowRight from '/public/svg/down-arrow.svg'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <span>aaaa</span>
          <ArrowRight
            height={48}
            width={48}
            fill={'red'}
            stroke={'red'}
            strokeWidth={2}
          />

          <img src="/arrow-type-1-right.png" alt="" width={16} height={16} />
        </div>
      </main>
    </>
  )
}
